<a href="https://colab.research.google.com/github/ana-clara-souza/machine-learning/blob/main/PI_0819_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Introdução ao Pandas

##NumPy
- Rápida
- Trabalha apenas com dados numericos
- 100% em C
- Armazenamento de dados na memória (melhor opção)

##Pandas
- Feito em cima do NumPy
- Armazena dados heterogeneos
- Várias colunas e linhas
- Estrutura interna:
- - Series (coluna do dataframe)
- - DataFrame (conjunbto todo)

In [ ]:
!pip install pandas #instalação

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#Criar meu primeiro dataframe

#Forma mais fácil: construir a partir de outra estrtura de dadoos, ex: dicionário

produtos = {
    "codigo":[101, 102, 103, 104],
    "nome":["Monitor", "Celular", "Teclado", "Mouse"],
    "preco":[800.00, 5000.00, 200, 100.00],
    "estoque":[5, 4, 10, 15]
}

In [ ]:
produtos.keys()
produtos.values()

dict_values([[101, 102, 103, 104], ['Monitor', 'Celular', 'Teclado', 'Mouse'], [800.0, 5000.0, 200, 100.0], [5, 4, 10, 15]])

In [ ]:
import pandas as pd

In [ ]:
#Gerar dataframe
df = pd.DataFrame(produtos) #quando chama devolve um objeto, df armazena ele

In [ ]:
df #visualização
#Chave - coluna
#Valores - linhas

   codigo     nome   preco  estoque
0     101  Monitor   800.0        5
1     102  Celular  5000.0        4
2     103  Teclado   200.0       10
3     104    Mouse   100.0       15

In [ ]:
#Propriedades
df.info()

#mostra os detalhes do dataframe
#mostra os dados faltantes
#tipo de dados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   codigo   4 non-null      int64
 1   nome     4 non-null      object
 2   preco    4 non-null      float64
 3   estoque  4 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 260.0+ bytes

In [ ]:
df.shape #mostra a dimensão

(4, 4)

In [ ]:
# Incluir nova coluna
#Total estoque ($) - baseada em preço

df['total Estoque'] = df['estoque'] * df['preco']

In [ ]:
df

   codigo     nome   preco  estoque  total Estoque
0     101  Monitor   800.0        5         4000.0
1     102  Celular  5000.0        4        20000.0
2     103  Teclado   200.0       10         2000.0
3     104    Mouse   100.0       15         1500.0

In [ ]:
df['total Estoque'].mean() #valor médio de custo da coluna

np.float64(6875.0)

In [ ]:
type(df)

pandas.core.frame.DataFrame

#Biblioteca Kaggle

O Kaggle é a maior plataforma online do mundo para ciência de dados e aprendizado de máquina (machine learning), pertencente ao Google. Ela reúne milhões de usuários para compartilhar dados, criar códigos na nuvem, participar de competições com prêmios em dinheiro e aprender novas técnicas de inteligência artificial

### Estudo de caso: Airline Passenger Satisfaction
(https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction)

In [ ]:
df = pd.read_csv("train.csv.zip", compression="zip") #leitor de csv e se estiver compactado ele descompacta

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df.isna().sum() #corre todas as colunas e soma os dados faltantes

# Exercícios práticos

In [ ]:
# #Estrtura inicial
# import pandas as pd
# produtos = {
#     "codigo":[1, 2, 3],
#     "nome":["teclado", "mouse", "caneta"],
#     "valores":[200, 100, 5],
#     "estoque":[10, 2, 50]
# }

# df = pd.DataFrame(produtos)

In [ ]:
# df

In [ ]:
#1. Inspeção das Dimensões

# df.shape

In [ ]:
#Informações e Tipos de Dados
# df.info()

In [ ]:
#3. Nova Coluna Calculada

# df['faturamento_potencial'] = df['valores']*df['estoque']

In [ ]:
#4. Estatística da Nova Coluna

# df['faturamento_potencial'].mean().sum()

In [ ]:
#5. Filtragem Simples de Registros

# df[df['valores']>5]

**Diferença Básica: .iloc vs .loc.iloc: **
 Usa posições numéricas inteiras (0, 1, 2...). Ignora o nome dos índices..loc: Usa os rótulos ou nomes reais das linhas e colunas.

In [ ]:
#6. Seleção por Posição (iloc)
#df.iloc[linhas, colunas]

# df.iloc[0] #retorna a primeria linha
# df.iloc[0:3] #retorna da primeria ate terceira linha
# df.iloc[0:2, 0:2] #seleciona as duas primeiras linhas e as duas primeiras colunas

#AULA 24/08

In [ ]:
df.describe()

In [ ]:
#remoção de colunas irrelevantes
# Unnamed:0
# remove as colunas chamadas 'Unnamed: 0' e 'id'
df = df.drop(columns=['Unnamed: 0', 'id'])

In [ ]:
df

In [ ]:
#substituir dados faltantes

media_atrasos = df['Arrival Delay in Minutes'].mean()
print(f"Média: {media_atrasos}")

In [ ]:
#preencher os dadfos faltantes pela média
#fillna -- roda o dataframe na coluna in dicada verificando todos os valores NaN e trocando pelo valor indicado
df['Arrival Delay in Minutes'] = df['Arrival Delay in Minutes'].fillna(media_atrasos)

In [ ]:
df

In [ ]:
df['Arrival Delay in Minutes'].mean()

In [ ]:
#precisa preencher os NaN por conta dos algoritmos de aprendizado de máquina, para de reduzir as chnaces de retornar erro

#investigando a base de dados

In [ ]:
df.columns

In [ ]:
#pesquisa na abse de dados
#df.loc - permite colocar o nome das colunas
#df.iloc(linha, coluna) --- utilizando o indice


df.loc[100:120, ['Gender', 'Customer Type', 'Age']]

In [ ]:
#valores das colunas categoricas
#colunas categoricas - são colunas com string

#descobrir colunas não númericas

cat_cols = df.select_dtypes(include='object').columns.tolist() #include é quais sao os dtypes que quero extrair, escolhe as colunas, transforma em uma lista tolist
print(cat_cols)

In [ ]:
#valores das colunas numericas

num_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()

In [ ]:
for col in cat_cols:
  print(f"{col} - {df[col].unique()}") #dados únicos da categoria

In [ ]:
# Filtro
#Operadores booleanos
# & (E)
# | (OU)
# ~ (NÃO)
filtro = ((df['Type of Travel']== 'Business travel') & #tipo de viagem business travel
          (df['Class']=='Eco') &
          (df['Flight Distance']>1500)

)

In [ ]:
filtro

In [ ]:
#aplicar o filtro booleano

dados_filtrados = df.loc[filtro, ['Age', 'Gender', 'Customer Type', 'satisfaction']]

In [ ]:
dados_filtrados

In [ ]:
len(df)